# Generated by Django 5.2.3 on 2025-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='apellidos',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='personas',
            name='edad',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nombres',
            field=models.CharField(max_length=25),
        ),
    ]
