# Generated by Django 5.2.3 on 2025-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_personas_apellidos_alter_personas_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='donador',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
