# Generated by Django 5.2.3 on 2025-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_personas_donador'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='correo',
            field=models.EmailField(default='sincorreo@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
