# Generated by Django 5.2.3 on 2025-06-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_personas_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=35)),
                ('edad', models.IntegerField()),
                ('donador', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Personas',
        ),
    ]
