# Generated by Django 5.2.3 on 2025-06-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celulares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celulares',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
